name: Prepare, build and distribute components package

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: projects/xplorecomponents
        run: npm install
      - name: Launch test
        working-directory: projects/xplorecomponents
        run: npm run test
  build-package:
    needs: test-package
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install dependencies
        working-directory: projects/xplorecomponents
        run: npm install
      - name: Build package
        working-directory: projects/xplorecomponents
        run: npm run test

  publish-npmjs:
    needs: build-package
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Publish to npmJS
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: dist/xplorecomponents/package.json 
  publish-chromatic:
    needs: build-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.CHROMATIC_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: dist/xplorecomponents
 
